{
    "petName": "cacacat",
    "petType": "dog",
    "petImg": "",
    "arrayResponses": [
        {"idx": 16, "response": 1, "questionType": "사교성"},
        {"idx": 1, "response": 1, "questionType": "활동성"},
        {"idx": 7, "response": -3, "questionType": "식탐성"},
        {"idx": 8, "response": -1, "questionType": "식탐성"},
        {"idx": 17, "response": 3, "questionType": "애교성"},
        {"idx": 16, "response": 1, "questionType": "사교성"},
        {"idx": 1, "response": 1, "questionType": "활동성"},
        {"idx": 7, "response": -3, "questionType": "식탐성"},
        {"idx": 8, "response": -1, "questionType": "식탐성"},
        {"idx": 17, "response": 3, "questionType": "애교성"},
        {"idx": 16, "response": 1, "questionType": "사교성"},
        {"idx": 1, "response": 1, "questionType": "활동성"},
        {"idx": 7, "response": -3, "questionType": "식탐성"},
        {"idx": 8, "response": -1, "questionType": "식탐성"},
        {"idx": 17, "response": 3, "questionType": "애교성"},
        {"idx": 16, "response": 1, "questionType": "사교성"},
        {"idx": 1, "response": 1, "questionType": "활동성"},
        {"idx": 7, "response": -3, "questionType": "식탐성"},
        {"idx": 8, "response": -1, "questionType": "식탐성"},
        {"idx": 17, "response": 3, "questionType": "애교성"}
    ],
}